server:
  port: 8087

spring:
  application:
    name: cloud-back_manager
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    register-with-eureka: true
    fetch-registry: true
